#!/bin/bash

set -xe

image="ubuntu:18.04"
tarname="bionic.tar"
rootdir="./root"

if ! [ -f "$tarname" ]; then
  docker export "$image" > "$tarname"
fi

if ! [ -d "$rootdir" ]; then
  mkdir "$rootdir"
  tar xf "$tarname" -C "$rootdir"
fi
