#!/bin/bash

set -xe

image="runtc-bionic"
tarname="$image.tar"
rootdir="../root"

if which docker > /dev/null; then
  if ! $(docker images --format '{{.Repository}}' | grep -q "$image"); then
    docker build . -t "$image"
  fi

  if ! [ -f "$tarname" ]; then
    docker run --name "$image" "$image"
    docker export "$image" > "$tarname"
    docker ps -a --filter "name=$image" -q | xargs docker rm
  fi
fi

if [ $(whoami) = 'vagrant' ] && ! [ -d "$rootdir" ]; then
  sudo mkdir "$rootdir"
  sudo tar xf "$tarname" -C "$rootdir"
fi
