#!/bin/bash

set -xe

image="ubuntu:18.04"
tarname="bionic.tar"
rootdir="../root"

if ! [ -f "$tarname" ]; then
  docker export "$image" > "$tarname"
fi

if [ $(whoami) = 'vagrant' ] && ! [ -d "$rootdir" ]; then
  sudo mkdir "$rootdir"
  sudo tar xf "$tarname" -C "$rootdir"
fi
